[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rabbit-rs-simple-single]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan rabbit-rs:work --queue=simple.default
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SUPERVISOR_RABBIT_RS_WORKERS)s
autorestart=true
stopsignal=TERM
stopasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rabbit-rs-cluster-single]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan rabbit-rs:work --queue=cluster.default
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SUPERVISOR_RABBIT_RS_WORKERS)s
autorestart=true
stopsignal=TERM
stopasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rabbit-rs-simple-all]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan rabbit-rs:work --queue=simple.all
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SUPERVISOR_RABBIT_RS_WORKERS)s
autorestart=true
stopsignal=TERM
stopasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rabbit-rs-cluster-all]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan rabbit-rs:work --queue=cluster.all
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SUPERVISOR_RABBIT_RS_WORKERS)s
autorestart=true
stopsignal=TERM
stopasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
